#!/bin/sh
# PROVIDE: devicemonitor
# REQUIRE: LOGIN DAEMON NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="devicemonitor"
desc="Device Monitor - network device tracking"
rcvar="${name}_enable"

load_rc_config ${name}

: ${devicemonitor_enable:="NO"}

pidfile="/var/run/${name}.pid"
procname="/usr/local/bin/python3"
command="/usr/sbin/daemon"
command_args="-f -p ${pidfile} /usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/DeviceMonitor/monitor_daemon.py"

run_rc_command "$1"